//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by P:\viewhtml\WIN32\VIEWHTML.RC
//
#define IDR_CNTR_INPLACE                6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_FAILED_TO_CREATE            102
#define IDC_URL_EDIT                    102
#define IDR_MAINFRAME                   128
#define IDR_CONTTYPE                    129
#define IDD_INSERTCTL                   130
#define IDR_MENU1                       130
#define IDD_OPEN_URL                    131
#define IDI_BAD_GIF                     131
#define IDC_HAND_CURSOR                 131
#define IDD_LOCATION_BAR                132
#define IDD_CNTL_DLG                    133
#define IDD_SAVE_URL                    136
#define IDD_BOOKMARKS                   137
#define IDD_EDIT_BOOKMARK               138
#define IDI_RED_LIGHT                   140
#define IDD_PREF_NETWORK                141
#define IDD_PREF_DIRECTORIES            142
#define IDD_SEND_MAIL                   142
#define IDD_PREF_USERINFO               143
#define IDD_PREF_OLE_CONTROLS           144
#define IDS_URL_TYPE_UNKNOWN            500
#define IDS_METHOD_TYPE_BAD             501
#define IDS_BAD_URL                     502
#define IDS_FILE_CANNOT_OPEN            503
#define IDS_FILE_EXCEPTION              504
#define IDC_LOCATION                    1000
#define IDC_BOOKMARK_LIST               1002
#define IDC_BUTTON_DELETE_ITEM          1003
#define IDC_BUTTON_MOVE_DOWN            1009
#define IDC_BUTTON_MOVE_UP              1010
#define IDC_BUTTON_EDIT_ITEM            1012
#define IDC_BUTTON_NEW_ITEM             1013
#define IDC_LIST_URL                    1014
#define IDC_EDIT_TITLE                  1016
#define IDC_EDIT_URL                    1017
#define IDC_BUTTON_OPEN_URL             1021
#define IDC_PRODUCT_NAME                1022
#define IDC_COMPANY_NAME                1023
#define IDC_FILE_DESCRIPTION            1024
#define IDC_SMTP_MAIL_SERVER            1024
#define IDC_PRODUCT_VERSION             1025
#define IDC_EDIT2                       1025
#define IDC_HTTP_PROXY                  1025
#define IDC_MESSAGE_TO                  1025
#define IDC_LEGAL_COPYRIGHT             1026
#define IDC_OCX_DIRECTORY               1026
#define IDC_LEGAL_TRADEMARKS            1027
#define IDC_CACHE_DIRECTORY             1027
#define IDC_HTTP_SITE                   1028
#define IDC_NUM_CONNECTIONS             1031
#define IDC_HOME_PAGE                   1032
#define IDC_LOAD_HOME_PAGE              1034
#define IDC_USER_NAME                   1035
#define IDC_USER_EMAIL                  1036
#define IDC_CLEAR_DISK_CACHE            1037
#define IDC_CHANGE_MEGABYTE             1039
#define IDC_CACHE_MEGABYTES             1040
#define IDC_CONTROL_LIST                1041
#define IDC_UNREGISTER_CONTROL          1042
#define IDC_PORT_NUMBER                 1043
#define IDC_PORT_TEXT                   1044
#define IDC_MESSAGE_BODY                1045
#define IDC_MESSAGE_SUBJECT             1046
#define IDC_MESSAGE_CC                  1047
#define ID_BOOKMARK00                   3000
#define ID_BOOKMARK01                   3001
#define ID_BOOKMARK02                   3002
#define ID_BOOKMARK03                   3003
#define ID_BOOKMARK04                   3004
#define ID_BOOKMARK05                   3005
#define ID_BOOKMARK06                   3006
#define ID_BOOKMARK07                   3007
#define ID_BOOKMARK08                   3008
#define ID_BOOKMARK09                   3009
#define ID_BOOKMARK10                   3010
#define ID_BOOKMARK11                   3011
#define ID_BOOKMARK12                   3012
#define ID_BOOKMARK13                   3013
#define ID_BOOKMARK14                   3014
#define ID_BOOKMARK15                   3015
#define ID_BOOKMARK16                   3016
#define ID_BOOKMARK17                   3017
#define ID_BOOKMARK18                   3018
#define ID_BOOKMARK19                   3019
#define ID_BOOKMARKS_MORE               3020
#define ID_VIEW_LOCATION_BAR            4000
#define ID_FILE_OPEN_URL                4001
#define ID_POPUP_1                      4002
#define ID_ACTIVATE_OCX                 4003
#define ID_ADD_BOOKMARK                 4003
#define ID_ACTIVATE_PROPERTIES          4004
#define ID_EDIT_BOOKMARKS               4004
#define ID_ACTIVATE_METHODS             4005
#define ID_GO_BACK                      4006
#define ID_GO_FORWARD                   4007
#define ID_GO_HOME                      4008
#define ID_RELOAD                       4009
#define ID_LOAD_IMAGES                  4010
#define ID_STOP_LOADING                 4012
#define ID_OPEN_LOCATION                4013
#define ID_OPTIONS_PREFERENCES          4014
#define IDC_CONTROLS                    4103
#define IDS_WINSOCK_HOST_LOOKUP_FAILED  5000
#define IDS_WSANOTINITIALISED           5000
#define IDS_WINSOCK_CREATE_FAILED       5001
#define IDS_WSAENETDOWN                 5001
#define IDS_WINSOCK_BIND_FAILED         5002
#define IDS_WSAEINPROGRESS              5002
#define IDS_WINSOCK_CONNECT_FAILED      5003
#define IDS_WSAEWOULDBLOCK              5003
#define IDS_WSAENOTSOCK                 5004
#define IDS_WINSOCK_SEND_ERROR          5005
#define IDS_WINSOCK_RECV_ERROR          5006
#define IDS_DNS_WSATRY_AGAIN            5100
#define IDS_DNS_WSAENOBUFS              5101
#define IDS_DNS_WSAHOST_NOT_FOUND       5102
#define IDS_DNS_WSANO_RECOVERY          5103
#define IDS_DNS_WSANO_DATA              5104
#define IDS_CON_WSAEADDRINUSE           5200
#define IDS_CON_WSAEADDRNOTAVAIL        5201
#define IDS_CON_WSAEAFNOSUPPORT         5202
#define IDS_CON_WSAECONNREFUSED         5203
#define IDS_CON_WSAEFAULT               5205
#define IDS_CON_WSAEINVAL               5206
#define IDS_CON_WSAEISCONN              5207
#define IDS_CON_WSAEMFILE               5208
#define IDS_CON_WSAENETUNREACH          5209
#define IDS_CON_WSAETIMEDOUT            5210
#define IDS_CON_WSAENOBUFS              5211
#define IDS_SEND_WSAEACCES              5300
#define IDS_SEND_WSAEFAULT              5301
#define IDS_SEND_WSAENETRESET           5302
#define IDS_SEND_WSAENOBUFS             5303
#define IDS_SEND_WSAEOPNOTSUPP          5304
#define IDS_SEND_WSAESHUTDOWN           5305
#define IDS_SEND_WSAEMSGSIZE            5306
#define IDS_SEND_WSAECONNABORTED        5307
#define IDS_SEND_WSAECONNRESET          5308
#define IDS_SEND_WSAENOTCONN            5309
#define IDS_SEND_WSAEINVAL              5310
#define IDS_RECV_WSAEMSGSIZE            5400
#define IDS_HTTP_AGENT_NAME             6000
#define IDS_HTTP_CONNECT_FAILED         6002
#define IDS_HTTP_SEND_FAILED            6003
#define IDS_HTTP_RECV_FAILED            6004
#define IDS_HTTP_ERROR_400              7400
#define IDS_HTTP_ERROR_401              7401
#define IDS_HTTP_ERROR_403              7403
#define IDS_HTTP_ERROR_404              7404
#define IDS_HTTP_ERROR_500              7500
#define IDS_HTTP_ERROR_501              7501
#define IDS_HTTP_ERROR_502              7502
#define IDS_HTTP_ERROR_503              7503
#define IDS_HTTP_ERROR_UNKNOWN          7504
#define IDS_AMODENAME_USERMODE          8000
#define IDS_AMODENAME_UIDEAD            8001
#define IDS_AMODENAME_DISPLAYHATCHING   8002
#define IDS_AMODENAME_DISPLAYGRABHANDLES 8003
#define IDS_APROPNAME_ACTIVECONTROL     8004
#define IDS_APROPNAME_TEXTALIGN         8005
#define IDS_APROPNAME_BACKCOLOR         8006
#define IDS_APROPNAME_FONT              8007
#define IDS_APROPNAME_FORECOLOR         8008
#define IDS_APROPNAME_SCALEUNITS        8009
#define IDS_APROPNAME_DISPLAYNAME       8011
#define IDS_APROPNAME_LOCALEID          8012
#define IDS_APROPNAME_MESSAGEREFLECT    8013
#define IDS_APROPNAME_USERDIRECTORY     8014
#define IDS_VTBOOL                      8200
#define IDS_VTI2                        8201
#define IDS_VTI4                        8202
#define IDS_VTR4                        8203
#define IDS_VTBSTR                      8204
#define IDS_VTCOLOR                     8205
#define IDS_VTFONT                      8206
#define IDS_VTOTHER                     8207
#define IDS_BOUNDPROP_PARAMS_ELLIPSIS   20001
#define IDS_BOUNDPROP_CHANGED           20002
#define IDS_BOUNDPROP_PREFIX            20003
#define IDS_BOUNDPROP_REQEDIT           20004
#define IDS_BOUNDPROP_REQEDIT_YES       20005
#define IDS_BOUNDPROP_REQEDIT_NO        20006
#define ID_CANCEL_EDIT_CNTR             32768

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         4015
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
